Sampling homework part 1
annalimm/First_hmw pull request #3
Opened 2019-11-10 23:20 UTC by annalimm

2019-11-17 10:09 UTC, illarionovEA requested changes
задание недоделано
длина траектории блуждания должна быть ровно 100 (при этом начало и конец в 0)

2019-12-26 14:35 UTC, illarionovEA commented
нет задачи на генерацию подмножеств

2019-12-26 22:53 UTC, bbuusshh commented
Добавлена задача на генерацию подмножеств.

2019-12-26 23:31 UTC, annalimm commented
https://www.codewars.com/users/annalimm

2019-12-26 23:42 UTC, closed without merging